In [52]:
import pandas as pd 
import json 

with open("./petrolofisi.json", "r", encoding="utf-8") as fp:
    petrolofisi_data = fp.read()

petrolofisi_stations =[]


for i in json.loads(petrolofisi_data.encode("utf-8")):
    for j in i["Values"]:
        petrolofisi_stations.append(j)




df_petrolofisi = pd.DataFrame(petrolofisi_stations)

In [53]:
with open("./aytemiz.json", "r", encoding="utf-8") as fp:
    aytemiz_data = fp.read()

aytemiz_stations =[]


for i in json.loads(aytemiz_data.encode("utf-8")):
    aytemiz_stations.append(i)

df_aytemiz = pd.DataFrame(aytemiz_stations)

In [54]:
with open("./shell.json", "r", encoding="utf-8") as fp:
    shell_data = fp.read()

shell_stations =[]


for i in json.loads(shell_data.encode("utf-8")):
    shell_stations.append(i)

df_shell = pd.DataFrame(shell_stations)

In [55]:
with open("./tp.json", "r", encoding="utf-8") as fp:
    tp_data = fp.read()

tp_stations =[]


for i in json.loads(tp_data.encode("utf-8")):
    tp_stations.append(i)

df_tp = pd.DataFrame(tp_stations)

In [61]:
df_tp

,StationName,Lat,Lng,Address,County,CityName,CityId,StationType,VIS,KursunsuzBenzin,TpMotorin,TpGaz
0,10 NOLU AKARYAKIT,40.772354,29.754648,Mimar Sinan Mah. Eşref Bitlis Cad. No : 301 Kö...,KÖRFEZ,KOCAELİ,41,1,True,0,0,0
1,3E PETROL,40.532223,30.304200,Epçeler Mahallesi Ankara Caddesi No:19 Karapın...,GEYVE,SAKARYA,54,1,True,0,0,0
2,4YOL AKARYAKIT,36.866200,36.215800,Altınçağ Mahallesi Atatürk Caddesi No:10/2 DÖR...,DÖRTYOL,HATAY,31,1,True,0,0,0
3,ABDULKADİR EROĞLU PETROL,37.734100,38.235400,Altınşehir Mahallesi Gazihan Caddesi No:56 MER...,MERKEZ,ADIYAMAN,2,1,True,0,0,0
4,Abdullah ÇELEN,38.295864,35.583935,Epçe Köyü DEVELİ KAYSERİ,DEVELİ,KAYSERİ,38,1,False,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
814,Zekayi KARACA,40.284320,30.118504,Medetli Köyü Osmaneli / BİLECİK OSMANELİ BİLECİK,OSMANELİ,BİLECİK,11,1,False,0,0,0
815,ZENGİN PETROL,41.001465,40.547688,Dereüstü Mahallesi İçmeler Caddesi No:70 MERKE...,MERKEZ,RİZE,53,1,True,0,0,0
816,ZORBEY PETROL,36.710163,37.193900,Doğan Güreş Paşa Mahallesi Gaziantep Yolu Küme...,MERKEZ,KİLİS,79,1,True,0,0,0
817,ZÜMRA PETROL İSTANBUL,40.967180,29.215782,Fatih Mahallesi Yakacık Caddesi No:24 SANCAKTE...,SANCAKTEPE,İSTANBUL,34,1,True,0,0,0
818,ZÜMRA PETROL KOCAELİ,40.862102,29.387701,Şekerpınar Mahallesi Muhsin Yazıcıoğlu Caddesi...,ÇAYIROVA,KOCAELİ,41,1,True,0,0,0

In [78]:
df_tp = df_tp.rename(columns={"CityName" : "City","County": "County","Lat":"Lat","Lng": "Lon"})
df_petrolofisi = df_petrolofisi.rename(columns= {"DistrictName": "City","CityName": "County","Latitude":"Lat","Longitude": "Lon"})

In [96]:
df_tp

,StationName,Lat,Lon,Address,County,City,CityId,StationType,VIS,KursunsuzBenzin,TpMotorin,TpGaz
0,10 NOLU AKARYAKIT,40.772354,29.754648,Mimar Sinan Mah. Eşref Bitlis Cad. No : 301 Kö...,KÖRFEZ,KOCAELİ,41,1,True,0,0,0
1,3E PETROL,40.532223,30.304200,Epçeler Mahallesi Ankara Caddesi No:19 Karapın...,GEYVE,SAKARYA,54,1,True,0,0,0
2,4YOL AKARYAKIT,36.866200,36.215800,Altınçağ Mahallesi Atatürk Caddesi No:10/2 DÖR...,DÖRTYOL,HATAY,31,1,True,0,0,0
3,ABDULKADİR EROĞLU PETROL,37.734100,38.235400,Altınşehir Mahallesi Gazihan Caddesi No:56 MER...,MERKEZ,ADIYAMAN,2,1,True,0,0,0
4,Abdullah ÇELEN,38.295864,35.583935,Epçe Köyü DEVELİ KAYSERİ,DEVELİ,KAYSERİ,38,1,False,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
814,Zekayi KARACA,40.284320,30.118504,Medetli Köyü Osmaneli / BİLECİK OSMANELİ BİLECİK,OSMANELİ,BİLECİK,11,1,False,0,0,0
815,ZENGİN PETROL,41.001465,40.547688,Dereüstü Mahallesi İçmeler Caddesi No:70 MERKE...,MERKEZ,RİZE,53,1,True,0,0,0
816,ZORBEY PETROL,36.710163,37.193900,Doğan Güreş Paşa Mahallesi Gaziantep Yolu Küme...,MERKEZ,KİLİS,79,1,True,0,0,0
817,ZÜMRA PETROL İSTANBUL,40.967180,29.215782,Fatih Mahallesi Yakacık Caddesi No:24 SANCAKTE...,SANCAKTEPE,İSTANBUL,34,1,True,0,0,0
818,ZÜMRA PETROL KOCAELİ,40.862102,29.387701,Şekerpınar Mahallesi Muhsin Yazıcıoğlu Caddesi...,ÇAYIROVA,KOCAELİ,41,1,True,0,0,0

In [89]:
df_aytemiz["Lat"] = df_aytemiz["Lat"].astype(np.float64)
df_aytemiz["Lon"] = df_aytemiz["Lon"].astype(np.float64)

In [ ]:
class unicode_tr(str):
    CHARMAP = {
        "to_upper": {
            u"ı": u"I",
            u"i": u"İ",
            u"ş": u"Ş",
            u"ğ": u"Ğ",
            u"ç": u"Ç",
            u"ö": u"Ö",
        },
        "to_lower": {
            u"I": u"ı",
            u"İ": u"i",
            u"Ş": u"ş",
            u"Ğ": u"ğ",
            u"Ç": u"ç",
            u"Ö": u"ö",
        }
    }

    def lower(self):
        for key, value in self.CHARMAP.get("to_lower").items():
            self = self.replace(key, value)
        return self.lower()

    def upper(self):
        for key, value in self.CHARMAP.get("to_upper").items():
            self = self.replace(key, value)
        return self.upper()

In [145]:
import locale
locale.setlocale(locale.LC_ALL, "tr_TR.utf8")
columns = ["City","County","Lat","Lon"]

df1 = df_petrolofisi[columns]
df2 = df_aytemiz[columns]
df3 = df_tp[columns]




df = pd.concat([df1,df2,df3],axis= 0)

ModuleNotFoundError: No module named 'openpyxl'